name: tokenapp
description: The tokenapp App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  get: ^4.1.4

  # Network
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1

  # User interface
  fluttertoast: ^8.0.7
  webview_flutter: ^3.0.0
  flutter_local_notifications: ^9.2.0
  percent_indicator: ^3.3.0-nullsafety.1
  flutter_staggered_grid_view: ^0.5.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  cached_network_image: ^3.1.0
  flutter_spinkit: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  image_picker: ^0.8.2
  custom_check_box: ^0.0.4
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.0
  geocoding: ^2.0.1
  flutter_google_places: ^0.3.0
  screenshot: ^1.2.3
  simple_tooltip: ^1.0.0
  dotted_line: ^3.1.0
  simple_gradient_text: ^1.2.2
  country_code_picker: ^2.0.2
  webview_flutter_plus: ^0.3.0+2

  # Data
  get_storage: ^2.0.1
  intl: ^0.17.0
  json_annotation: ^4.0.0
  url_launcher: ^6.0.2
  path_provider: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.7
  logger: ^1.1.0
  flutter_html: ^3.0.0-alpha.1
  launch_review: ^3.0.1
  image_gallery_saver: '^1.7.1'
  badges: ^2.0.2
  dotted_border: ^2.0.0+2
  confetti: ^0.6.0

  #Firebase
  firebase_core: ^1.10.6
  #firebase_messaging: ^11.2.4



dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^6.1.3
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icons/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/icon_img/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/manrope_extra_light.ttf
          weight: 200
        - asset: fonts/manrope_light.ttf
          weight: 300
        - asset: fonts/manrope_regular.ttf
          weight: 400
        - asset: fonts/manrope_medium.ttf
          weight: 500
        - asset: fonts/manrope_semi_bold.ttf
          weight: 600
        - asset: fonts/manrope_bold.ttf
          weight: 700
        - asset: fonts/manrope_extra_bold.ttf
          weight: 800

    - family: Nunito Sans
      fonts:
        - asset: fonts/nunito_sans_extra_light.ttf
          weight: 200
        - asset: fonts/nunito_sans_light.ttf
          weight: 300
        - asset: fonts/nunito_sans_regular.ttf
          weight: 400
        - asset: fonts/nunito_sans_semi_bold.ttf
          weight: 600
        - asset: fonts/nunito_sans_bold.ttf
          weight: 700
        - asset: fonts/nunito_sans_extra_bold.ttf
          weight: 800
        - asset: fonts/nunito_sans_black.ttf
          weight: 900
